### ISSUE TITLE
bug(android): org.json.JSONException index out of range

### ISSUE THREAD

**Issue by losadaem** [EinfachHans/cordova-plugin-advanced-nativeaudio#1]
When using `preloadSimple(...)` on Android it always fails with a JSON Exception.

[cordova-plugin-nativeaudio](https://github.com/wizpanda/cordova-plugin-nativeaudio) is not raising the exception.

**Comment by EinfachHans** [comment]
Any Error Output on the console?

**Comment by losadaem** [comment]
I've just found the error. I've made a pull request.

**Comment by losadaem** [comment]
Hi, any update on this ?

**Comment by EinfachHans** [comment]
see pr
